// Legal content rendered inside ArticleModal. `tag` becomes the eyebrow
// in the modal, `minutes` becomes the right-side meta label.
const TODAY = "Updated February 2026";

export const PRIVACY_POLICY = {
  id: "privacy-policy",
  tag: "Privacy Policy",
  title: "Privacy Policy",
  minutes: TODAY,
  body: [
    "MiCells® (\"MiCells®\", \"we\", \"us\" or \"our\") is committed to protecting the privacy of every individual, family office and institution that interacts with us through this website. This Privacy Policy explains what information we collect, how we use it and the choices you have in relation to it.",
    "Information you provide directly. When you submit an enquiry through our contact form, you choose to share your name, organisation (where applicable), email address, country of residence and the content of your message. We treat this information as confidential and use it solely for the purpose of responding to your enquiry and any subsequent correspondence you initiate with us.",
    "Information collected automatically. When you visit our website, our hosting infrastructure may automatically log standard technical information such as your IP address, browser type, device characteristics, the pages you view and the time of your visit. This information is used to maintain site availability, protect against abuse and improve the experience offered to legitimate visitors.",
    "Cookies and similar technologies. We aim to minimise the use of cookies. Where cookies are used, they are limited to functions strictly necessary for the operation of the website. We do not currently use advertising cookies or sell data to advertising networks.",
    "How we use your information. We use the information described above to respond to enquiries, to fulfil any obligations agreed with you, to maintain the integrity and security of our infrastructure, to comply with applicable legal and regulatory requirements, and to communicate with you in relation to topics you have expressly raised with us.",
    "Lawful basis. Where required, we rely on your consent (provided by your voluntary submission of the contact form), the necessity of taking steps at your request prior to entering into any service relationship, and our legitimate interest in operating, securing and improving the website.",
    "Sharing of information. We do not sell, rent or trade personal information. We share information only with carefully selected service providers acting on our behalf (for example, transactional email delivery and infrastructure providers), and only to the extent strictly necessary to provide the services you have requested or that we lawfully use. All such providers are required to handle data confidentially and in compliance with applicable law.",
    "International transfers. As we operate internationally, your information may be processed in jurisdictions outside the country in which you reside. Where this is the case, we take appropriate steps to ensure that your information continues to receive a level of protection consistent with this Policy.",
    "Data retention. We retain enquiry information for as long as is reasonably necessary to respond to your enquiry, to maintain a coherent record of correspondence and to comply with applicable legal, regulatory and audit obligations. Where information is no longer required, it is securely deleted or anonymised.",
    "Your rights. Subject to applicable law, you may request access to the personal information we hold about you, request correction of inaccurate information, request deletion of information that is no longer required, restrict or object to certain processing activities and request that your information be transferred to you in a portable format. To exercise any of these rights please contact us using the details below.",
    "Security. We apply organisational, technical and procedural safeguards designed to protect the information you share with us against unauthorised access, alteration, disclosure or destruction. While no system can be guaranteed entirely secure, we treat the protection of the information you provide as a core operational priority.",
    "Children. This website is not directed at children and we do not knowingly collect information from individuals under the age of eighteen. If you believe a minor has submitted information to us, please contact us and we will take appropriate steps to delete it.",
    "Changes to this Policy. We may update this Privacy Policy from time to time to reflect changes in our practices, services or the legal and regulatory environment. The date at the top of this document indicates when it was last revised. Material changes will be communicated through the website in a prominent manner.",
    "Contact. Privacy enquiries, including the exercise of any of the rights described above, should be directed in writing to info@micells.io. We aim to respond to all reasonable requests within the timeframes required by applicable law.",
  ],
};

export const TERMS_OF_USE = {
  id: "terms-of-use",
  tag: "Terms of Use",
  title: "Terms of Use",
  minutes: TODAY,
  body: [
    "These Terms of Use govern your access to and use of this website operated by MiCells® (the \"Site\"). By accessing or using the Site you agree to be bound by these Terms. If you do not agree, please do not use the Site.",
    "Purpose of the Site. The Site is published for informational purposes only. It describes MiCells®, its intended areas of activity in the field of long-term personal blood banking and biological assurance, and provides a channel through which qualified parties may contact us. The Site does not constitute an offer of services, an offer of securities, an invitation to invest or the rendering of professional medical, clinical, legal, regulatory or financial advice.",
    "No medical advice. Nothing on this Site is intended to constitute medical advice, diagnosis or treatment. Any decision concerning your health, treatment, preservation of biological material or related matters must be taken in consultation with appropriately qualified medical professionals and, where relevant, your own legal and financial advisers. MiCells® expressly disclaims any responsibility for any action taken in reliance on information presented on the Site.",
    "No offer of securities. References to investor enquiries, partnerships or strategic discussions on the Site are intended solely to facilitate confidential dialogue with qualified parties. They do not constitute an offer to sell, or a solicitation of an offer to buy, any security or interest in any entity, and they should not be construed as such in any jurisdiction.",
    "Forward-looking statements. The Site may contain statements regarding intended services, future activities, infrastructure plans and the development of governance frameworks. Such statements reflect current expectations and are subject to risks, uncertainties and changes in circumstance. Actual outcomes may differ materially.",
    "Confidentiality of communications. Communications submitted through the Site are treated as confidential by MiCells®. However, transmissions over the internet cannot be guaranteed to be entirely secure, and you should not include in any submission information you consider highly sensitive without first agreeing a more secure communication channel with us.",
    "Intellectual property. All content on the Site, including text, graphics, logos, images, video and the underlying design, is owned by or licensed to MiCells® and is protected by applicable intellectual property laws. You may view and download content from the Site for your own personal and non-commercial reference only. Any other use, including reproduction, modification, distribution, transmission or publication, requires our prior written consent.",
    "Trade marks. The MiCells® name, the MiCells® hexagonal mark and related design elements are trade marks of MiCells®. They may not be used in connection with any product, service or activity without our prior written consent.",
    "Third-party links and content. The Site may from time to time link to third-party websites or reference third-party content. Such links and references are provided for convenience only. MiCells® does not endorse, control or accept responsibility for the content, accuracy or practices of third parties.",
    "Acceptable use. You agree not to use the Site in any manner that is unlawful, that interferes with its operation, that attempts to gain unauthorised access to any system or data, that involves the transmission of malicious code, or that infringes the rights of MiCells® or any third party. We reserve the right to restrict or terminate access in response to any such conduct.",
    "Disclaimer of warranties. The Site is provided on an \"as is\" and \"as available\" basis. To the maximum extent permitted by applicable law, MiCells® disclaims all warranties of any kind, whether express or implied, including without limitation warranties of merchantability, fitness for a particular purpose, non-infringement and accuracy.",
    "Limitation of liability. To the maximum extent permitted by applicable law, MiCells® shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits, revenues, data or opportunities, arising out of or in connection with your use of, or inability to use, the Site, even if MiCells® has been advised of the possibility of such damages.",
    "Indemnity. You agree to indemnify and hold harmless MiCells®, its officers, employees, advisers and affiliates from and against any claims, liabilities, costs and expenses arising out of any breach by you of these Terms or any misuse of the Site.",
    "Governing law. These Terms are governed by the laws of the Hong Kong Special Administrative Region. Any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the Hong Kong courts, save where mandatory law of your country of residence provides otherwise.",
    "Changes to these Terms. We may revise these Terms from time to time. Revisions take effect upon publication on the Site. Your continued use of the Site after publication constitutes acceptance of the revised Terms.",
    "Contact. Questions concerning these Terms or any aspect of the Site may be directed in writing to info@micells.io.",
  ],
};
